version: 0.2

phases:
  pre_build:
    commands:
      - echo "Switching to the application directory"
      - cd sample-app
      - echo "Pulling the hadolint docker image"
      - docker pull hadolint/hadolint:v1.16.2
  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Scanning with Hadolint..."
      - result=`docker run --rm -i -v ${PWD}/hadolint.yml:/.hadolint.yml hadolint/hadolint:v1.16.2 hadolint -f json - < Dockerfile`
  post_build:
    commands:
      - echo "Lint Results:"
      - echo $result | jq .
      - aws ssm put-parameter --name "codebuild-dockerfile-results" --type "String" --value "$result" --overwrite
      - echo Build completed on `date`