addons:
  sonarcloud:
    organization: "ramona484"
    token: $SONAR_TOKEN


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner